---
#- hosts: syscert
- hosts: localhost
  tasks:

    # Account Mgmt. : U-103 / high
    - name : Remove unnecessary account
      ansible.builtin.file:
        path: /etc/passwd
        regexp: '^{{ account }}:'
        state: absent
      loop:
        - adm
        - lp
        - shutdown
        - halt
        - news
        - uucp
        - operator
        - games
        - gopher
        - ftp
        - video
        - tape
        - audio
        - floppy
        - dialout
      loop_control:
        loop_var: account
    
    # Account Mgmt. : U-112 / law
    - name : Remove unnecessary group
      ansible.builtin.file:
        path: /etc/group
        regexp: '^{{ group }}:'
        state: absent
      loop:
        - sys
        - tty
        - disk
        - mem
        - kmem
        - cdrom
        - man
        - dialout
        - floppy
        - games
        - tape
        - video
        - lock
        - audio
        - utmp
        - utempter
        - input
        - systemd-journal
        - ssh_keys
        - postdrop
        - screen
        - printadmin
        - cgred
        - docker
        - stapusr
        - stapsys
        - stapdev
      loop_control:
        loop_var: group

    # File and Directory Mgmt. : U-403 / high
    - name: /etc/hosts file ownership & permission 
      ansible.builtin.file:
        path: /etc/hosts
        owner: root
        group: root
        mode: '0600'

    # File and Directory Mgmt. : U-404 / high
    - name: /etc/xinetd.conf, /etc/xinetd.d/* file/directory ownership & permission 
      ansible.builtin.file:
        path: /etc/xinetd.d/
        owner: root
        group: root
        mode: '0600'
        recurse: true
    
    # Permissions Mgmt. : U-406 / high
    - name: /sbin/unix_chkpwd file remove suid
      ansible.builtin.file:
        path: /sbin/unix_chkpwd
        mode: -s
    - name: /usr/bin/at file remove suid
      ansible.builtin.file:
        path: /usr/bin/at
        mode: -s
    - name: /usr/bin/newgrp remove suid
      ansible.builtin.file:
        path: /usr/bin/newgrp
        mode: -s
    
    # Service Mgmt. : U-315 / medium
    - name: /etc/at.deny other -r 
      ansible.builtin.file:
        path: /etc/at.deny
        mode: '640'
#    - name: /usr/bin/su 
#      ansible.builtin.file:
#        path: /usr/bin/su
#        group: wheel
#        mode: '4750'

    # account Mgmt. : U-304 / high
    - name: SU Command Restriction
      ansible.builtin.file:
        path: "{{ su.path }}"
        group: wheel
        mode: '4750'
      loop:
        - { path: '/bin/su' }
        - { path: '/usr/bin/su' }
      loop_control:
        loop_var: su    
    
    # Account Mgmt. : U-104 / medium
    - name: Set Password Expiration Days
      ansible.builtin.lineinfile:
        path: '/etc/login.defs'
        regexp: '^PASS_MAX_DAYS[\s\x20]*[0-9]*'
        line: "PASS_MAX_DAYS 90"
        state: present
    
    - name: Set Password Min Days
      ansible.builtin.lineinfile:
        path: '/etc/login.defs'
        regexp: '^PASS_MIN_DAYS[\s\x20]*[0-9]*'
        line: "PASS_MIN_DAYS 1"
        state: present

    - name: Set Password Min Length
      ansible.builtin.lineinfile:
        path: '/etc/login.defs'
        regexp: '^PASS_MIN_LEN[\s\x20]*[0-9]*'
        line: "PASS_MIN_LEN 8"
        state: present

    # File and Directory Mgmt. : U-303 / medium
    - name: Ensure umask 022 in /etc/profile
      ansible.builtin.lineinfile:
        path: '/etc/profile'      
        line: "umask 022"
        state: present
    
    - name: Export umask
      ansible.builtin.lineinfile:
        path: '/etc/profile'
        insertafter: '^umask 022'
        line: "export umask"
    
    # Access Mgmt. : U-306 / low
    - name: Ensure session timeout 600s
      ansible.builtin.lineinfile:
        path: '/etc/profile'
        line: "TMOUT=600"
        state: present

    - name: Export TMOUT
      ansible.builtin.lineinfile:
        path: '/etc/profile'
        insertafter: '^TMOUT=600'
        line: "export TMOUT"
    
    # Service Mgmt. : U-201 / low
    - name: Ensure Server Logon message
      ansible.builtin.lineinfile:
        path: '/etc/motd'
        insertbefore: BOF
        line: "-- WARNING -- This system is for the use of authorized users only. Individuals using this computer system without authority or in excess of their authority are subject to having all their activities on this system monitored and recorded by system personnel. Anyone using this system expressly consents to such monitoring and is advised that if such monitoring reveals possible evidence of criminal activity system personal may provide the evidence of such monitoring to law enforcement officials."
        state: present

    - name: Ensure Telnet Logon message
      ansible.builtin.lineinfile:
        path: '/etc/issue.net'
        line: "-- WARNING -- This system is for the use of authorized users only. Individuals using this computer system without authority or in excess of their authority are subject to having all their activities on this system monitored and recorded by system personnel. Anyone using this system expressly consents to such monitoring and is advised that if such monitoring reveals possible evidence of criminal activity system personal may provide the evidence of such monitoring to law enforcement officials."
        state: present

    #  Service Management : U-314 / medium
    - name: Ensure ftp shell false
      ansible.builtin.replace:
        path: '/etc/passwd'
        regexp: '^ftp(.*)\/sbin\/nologin$'
        replace: 'ftp\1/bin/false'