---
# dry-run to check modification:
#   - ansible-playbook your-playbook.yml --check --diff

# To run using '--tag'
#  - set 'true' of the specific vars and 
#  - dry-run: ansible-playbook your-playbook.yml --tags "U103_tag" --check --diff 
#  - run: ansible-playbook your-playbook.yml --tags "U103_tag" 



#- hosts: syscert                 # based on the 'hosts' file with target 'syscert' 
- hosts: localhost
  vars:
    U103_remove_account: false    # Account Mgmt. : U-103 / high              / tags: U103_tag
    U112_remove_group: false      # Account Mgmt. : U-112 / law               / tags: U112_tag
    U403_hosts_permission: true   # File and Directory Mgmt. : U-403 / high   / tags: U403_tag
    U404_xinetd_perission: true   # File and Directory Mgmt. : U-404 / high   / tags: U404_tag
    U406_remove_suid: true        # Permissions Mgmt. : U-406 / high          / tags: U406_tag
    U315_atdeny_permission: true  # Service Mgmt. : U-315 / medium            / tags: U315_tag
    U304_su_restriction: true     # Account Mgmt. : U-304 / high              / tags: U304_tag
    U104_pwd_expiration: true     # Account Mgmt. : U-104 / medium            / tags: U104_tag
    U110_pwd_min_day: true        # Account Mgmt. : U-110 / medium            / tags: U110_tag
    U108_pwd_min_len: true        # Account Mgmt. : U-108 / medium            / tags: U108_tag
    U303_umask_profile: true      # File and Directory Mgmt. : U-303 / medium / tags: U303_tag
    U306_set_tmout: true          # Access Mgmt. : U-306 / low                / tags: U306_tag
    U306_fix_tmout: true          # To fix TMOUT readonly alert message       / tags: U306_fix_tag
    U201_server_logon_msg: true   # Service Mgmt. : U-201 / low               / tags: U201_server_tag
    U201_telnet_logon_msg: true   # Service Mgmt. : U-201 / low               / tags: U201_telnet_tag
    U314_ftp_shell_false: true    # Service Management : U-314 / medium       / tags: U314_tag
  
  tasks:
    # Account Mgmt. : U-103 / high
    - name : Remove unnecessary account
      ansible.builtin.lineinfile:
        path: /etc/passwd
        regexp: '^{{ account }}:'
        state: absent
      loop:
        - adm
        - lp
        - sync
        - news
        - uucp
        - games
        - gopher
        - ftp
      loop_control:
        loop_var: account
      when: U103_remove_account
      tags:
        - U103_tag
    
    # Account Mgmt. : U-112 / law
    - name : Remove unnecessary group
      ansible.builtin.lineinfile:
        path: /etc/group
        regexp: '^{{ group }}:'.
        state: absent
      loop:
      loop_control:
        loop_var: group
      when: U112_remove_group
      tags:
        - U112_tag

    # File and Directory Mgmt. : U-403 / high
    - name: /etc/hosts file ownership & permission 
      ansible.builtin.file:
        path: /etc/hosts
        owner: root
        group: root
        mode: '0600'
      when: U403_hosts_permission
      tags:
        - U403_tag

    # File and Directory Mgmt. : U-404 / high
    - name: /etc/xinetd.conf, /etc/xinetd.d/* file/directory ownership & permission 
      ansible.builtin.file:
        path: /etc/xinetd.d/
        owner: root
        group: root
        mode: '0600'
        recurse: true
      when: U404_xinetd_perission
      tags:
        - U404_tag
    
    # Permissions Mgmt. : U-406 / high
    - name: remove suid
      ansible.builtin.file:
        path: "{{ suid.path }}"
        mode: -s
      loop:
        - { path: '/sbin/unix_chkpwd' } 
        - { path: '/usr/bin/at' }
        - { path: '/usr/bin/newgrp' }
      loop_control:
        loop_var: suid
      when: U406_remove_suid
      tags:
        - U406_tag

    # Service Mgmt. : U-315 / medium
    - name: /etc/at.deny other -r 
      ansible.builtin.file:
        path: /etc/at.deny
        mode: '640'
      when: U315_atdeny_permission

    - name: SU Command Restriction
      ansible.builtin.file:
        path: "{{ su.path }}"
        group: wheel
        mode: '4750'
      loop:
        - { path: '/bin/su' }
        - { path: '/usr/bin/su' }
      loop_control:
        loop_var: su
      when: U304_su_restriction
      tags:
        - U315_tag
    
    # Account Mgmt. : U-104 / medium
    - name: Set Password Expiration Days
      ansible.builtin.lineinfile:
        path: '/etc/login.defs'
        regexp: '^PASS_MAX_DAYS[\s\x20]*[0-9]*'
        line: "PASS_MAX_DAYS 90"
        state: present
      when: U104_pwd_expiration
      tags:
        - U104_tag
    
    # Account Mgmt. : U-110 / medium
    - name: Set Password Min Days
      ansible.builtin.lineinfile:
        path: '/etc/login.defs'
        regexp: '^PASS_MIN_DAYS[\s\x20]*[0-9]*'
        line: "PASS_MIN_DAYS 1"
        state: present
      when: U110_pwd_min_day
      tags:
        - U110_tag

    # Account Mgmt. : U-108 / medium
    - name: Set Password Min Length
      ansible.builtin.lineinfile:
        path: '/etc/login.defs'
        regexp: '^PASS_MIN_LEN[\s\x20]*[0-9]*'
        line: "PASS_MIN_LEN 8"
        state: present
      when: U108_pwd_min_len
      tags:
        - U108_tag

    # File and Directory Mgmt. : U-303 / medium
    - name: Ensure umask 022 in /etc/profile
      ansible.builtin.lineinfile:
        path: '/etc/profile'      
        line: "umask 022"
        state: present
      when: U303_umask_profile
      tags:
        - U303_tag
      
    - name: Export umask
      ansible.builtin.lineinfile:
        path: '/etc/profile'
        insertafter: '^umask 022'
        line: "export umask"
      when: U303_umask_profile
      tags:
        - U303_tag
    
    # Access Mgmt. : U-306 / low
    - name: Ensure session timeout 600s
      ansible.builtin.lineinfile:
        path: '/etc/profile'
        line: "TMOUT=600"
        state: present
      when: U306_set_tmout
      tags:
        - U306_tag

    - name: Export TMOUT
      ansible.builtin.lineinfile:
        path: '/etc/profile'
        insertafter: '^TMOUT=600'
        line: "export TMOUT"
      when: U306_set_tmout
      tags:
        - U306_tag

    # To fix TMOUT readonly alert message regarding U-306
    - name: Comment out already set TMOUT in /etc/profile.d/screen.sh
      replace:
        dest: /etc/profile.d/screen.sh
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      with_items:
        - { regexp: '^\s(.*)TMOUT=', replace: '#\1TMOUT=' }
        - { regexp: '^\s(.*)export TMOUT$', replace: '#\1export TMOUT' }
        - { regexp: '^\s(.*)readonly TMOUT$', replace: '#\1readonly TMOUT' }
      when: U306_fix_tmout
      tags:
        - U306_fix_tag
    
    # Service Mgmt. : U-201 / low
    - name: Ensure Server Logon message
      ansible.builtin.lineinfile:
        path: '/etc/motd'
        insertbefore: BOF
        line: "-- WARNING -- This system is for the use of authorized users only. Individuals using this computer system without authority or in excess of their authority are subject to having all their activities on this system monitored and recorded by system personnel. Anyone using this system expressly consents to such monitoring and is advised that if such monitoring reveals possible evidence of criminal activity system personal may provide the evidence of such monitoring to law enforcement officials."
        state: present
      when: U201_server_logon_msg
      tags:
        - U201_server_tag

    - name: Ensure Telnet Logon message
      ansible.builtin.lineinfile:
        path: '/etc/issue.net'
        line: "-- WARNING -- This system is for the use of authorized users only. Individuals using this computer system without authority or in excess of their authority are subject to having all their activities on this system monitored and recorded by system personnel. Anyone using this system expressly consents to such monitoring and is advised that if such monitoring reveals possible evidence of criminal activity system personal may provide the evidence of such monitoring to law enforcement officials."
        state: present
      when: U201_telnet_logon_msg
      tags:
        - U201_telnet_tag
      

    # Service Management : U-314 / medium
    - name: Ensure ftp shell false
      ansible.builtin.replace:
        path: '/etc/passwd'
        regexp: '^ftp(.*)\/sbin\/nologin$'
        replace: 'ftp\1/bin/false'
      when: U314_ftp_shell_false
      tags:
        - U314_tag